### ISSUE TITLE
Update the layout for https://metacpan.org/

### ISSUE THREAD

**Issue by dhogan8** [metacpan/metacpan-web#2708] opened 2022-07-11 15:21 UTC
Attached are some potential updates to the layout of https://metacpan.org/. 

The branch [dhogan8/update-layout](https://github.com/metacpan/metacpan-web/tree/dhogan8/update-layout) is still a WIP pending feedback, but here is a list of some potential changes so far:

- Update header and remove icons
- Create a simple footer and remove sponsors
- Move the search to the nav menu except for the homepage
- Update the sidebar and change the screen size it toggles
**Note:** I haven't tested this layout on all pages yet.

<img width="2558" alt="about" src="https://user-images.githubusercontent.com/52248962/178298290-7c0dd898-aa53-4717-a0fd-3e5436b28d65.png">
<img width="2558" alt="author" src="https://user-images.githubusercontent.com/52248962/178298296-4231d103-9f30-4324-93e0-e1676c1ccf31.png">
<img width="1491" alt="faq medium" src="https://user-images.githubusercontent.com/52248962/178298300-216c9e1d-88fe-4e6d-9bfc-82fd6599c59a.png">
<img width="2558" alt="home - logged out" src="https://user-images.githubusercontent.com/52248962/178298303-968da778-3476-41ce-b9a7-d040316a8e1c.png">
<img width="1686" alt="home mobile" src="https://user-images.githubusercontent.com/52248962/178298307-f2412d27-4854-4345-b519-9a342a98531d.png">
<img width="1493" alt="metadata  medium" src="https://user-images.githubusercontent.com/52248962/178298309-294b786a-b063-4509-9c7f-33c448020cbe.png">
<img width="1678" alt="mobile slidepanel" src="https://user-images.githubusercontent.com/52248962/178298310-1cdd2f13-5dfe-4276-9dc6-764e44a9ccce.png">
<img width="1494" alt="news medium" src="https://user-images.githubusercontent.com/52248962/178298313-590a69bf-b8d1-4c50-8376-fd18c146674b.png">
<img width="2558" alt="pod" src="https://user-images.githubusercontent.com/52248962/178298317-df370307-7f29-4642-ada3-01a724791c5d.png">
<img width="2558" alt="pod renderer" src="https://user-images.githubusercontent.com/52248962/178298320-200be1b9-5423-42f3-ae5b-9c2eeec589e2.png">
<img width="2558" alt="pod2" src="https://user-images.githubusercontent.com/52248962/178298322-6d156f78-113e-494d-84d0-05f637f83742.png">
<img width="2558" alt="pod2 contents" src="https://user-images.githubusercontent.com/52248962/178298324-2f410d16-1a43-4bbb-bb3a-de2ac7008381.png">
<img width="2558" alt="tools - logged in" src="https://user-images.githubusercontent.com/52248962/178298332-49440877-64fb-4ebf-99e9-36c5a16b4b4c.png">

**Comment by oalders** [comment] 2022-07-11 16:01
I really like moving the search box to the top menu. Also the login on the top right seems much more compact and cleaner. This is going to look great on smaller devices. 

As far as tweaks go, we will need to preserve the sponsor logos in the footer and *probably* the StickerYou text as well.

**Comment by haarg** [comment] 2022-07-11 16:17
I like the general reorganization. Simplifying the header and moving items to the footer, and fixing some of the responsive design elements. Removing the dual sidebar thing.

We won't be able to remove the sponsor logos, so they will still need to be included in some form. Fixing them to work properly with the responsive design would be helpful.

Some of the files modified are vendor files, like bootstrap, which we won't want to modify. Hopefully it's reasonable to make the needed changes without touching those. I've wanted to switch to using SCSS and upgrading bootstrap for a while - that may help or hinder this.

Combining the sidebars is obviously still rather rough. I think we can remove some of the elements like contributors and plussers and link to external pages for them instead. Reordering the other elements could help as well. It is still a lot to have in one list though. There are a few categories of items. Informational, internal navigation, and external navigation. Some of those could possibly go elsewhere that wasn't a sidebar. Maybe some could be removed and placed only on the distribution page, rather than every module page.

The sidebar also seems to have a lot of empty space. Maybe that's OK, and I wouldn't notice if I wasn't so used to the current design. Maybe it would make sense to increase the font size slightly. There aren't many parts of the sidebar that can end up excessively wide. One is the distribution name, but I'm not sure it belongs there to begin with.

I'll try to try the branch out and give some more feedback later. Thanks a lot for working on this. Various parts of the UI have been rather rough for a while, and this feels like a good start at resolving them.

**Comment by dhogan8** [comment] 2022-07-17 15:10
Thanks for the feedback! 

Regarding the StickerYou and sponsors in the footer, here is a different potential layout. I'm not sure if the wording of the StickerYou needed to be exactly the same or could be stripped down a little bit.

I went ahead and moved the changes previously made to the Bootstrap less files into the into the `root/static/less/` files.

I agree the sidebar needs quite a bit of work. Some thoughts:
- I made the sidebar a bit wider than what it previously was because I set a max-width on the content for easier readability. As a result, this lead to more white space and the potential for a slightly wider sidebar. I think the extra space is okay because it allows some of the list items to breathe a bit more, which also allows for easier readability.
- Increasing the font-size a bit indeed makes sense.
- I removed most of the icons next to the list items since it was a bit busy and some of the icons seemed a bit forced rather than being helpful for describing the actual list item. 
- I'm not too sure which items should absolutely be placed in the sidebar for the author, distribution, pod, etc. pages, but I think the more we can pull out, the cleaner things will look. This will also allow users to find the most useful information that they may be looking for.

I do agree it makes sense to move to Bootstrap 5 and SCSS in the near future. Bootstrap 5 is much more responsive and easier to work with. I'm not sure if there is a preference for continuing with using Bootstrap 3 and less for now to set a good framework for those upgrades or if you wanted to make those upgrades prior to the redesign.
<img width="304" alt="home-sm" src="https://user-images.githubusercontent.com/52248962/179404566-cf6a057d-7ab5-4b72-beae-24cc0bee20bd.png">
<img width="674" alt="home-md" src="https://user-images.githubusercontent.com/52248962/179404567-d7d7a328-4de5-405f-9839-601ca08b3978.png">
<img width="1512" alt="home-lg" src="https://user-images.githubusercontent.com/52248962/179404568-feff59c1-067d-4aad-8029-d03c0a494a9a.png">

**Comment by waterkip** [comment] 2022-07-21 00:33
Just wanted to say that I love what I'm seeing. Looks really good, loving it!

**Comment by dhogan8** [comment] 2022-07-26 20:16
Here are some updated screenshots from the last batch:
- Removed some headers for the author page. Add in icons for email, location, website, etc.
- Removed some icons in the sidebar on the dist pages
- Removed StickerYou text from the homepage
- Removed the contact icon from the footer
- Change font color of the sidebar items to black
<img width="1507" alt="Screen Shot 2022-07-26 at 3 58 09 PM" src="https://user-images.githubusercontent.com/52248962/181102587-3cc1b8c0-7bee-4b3c-97da-aaf3bac61a1a.png">
<img width="1512" alt="Screen Shot 2022-07-26 at 4 02 24 PM" src="https://user-images.githubusercontent.com/52248962/181102593-f1bfe41f-c1c3-4c14-bdd2-d327984c6b04.png">
<img width="1512" alt="Screen Shot 2022-07-26 at 4 03 01 PM" src="https://user-images.githubusercontent.com/52248962/181102595-fc060fa4-306b-482b-9870-028b142fbbca.png">
<img width="1511" alt="Screen Shot 2022-07-26 at 4 16 06 PM" src="https://user-images.githubusercontent.com/52248962/181103944-1a676437-3612-422d-aed0-51620cf67035.png">

**Comment by oalders** [comment] 2022-07-26 21:21
This looks great! Especially the author and front page. I do notice that the Liquid Web logo is a bit hard to read. There are other versions here, if you need different assets to work with: https://www.liquidweb.com/about-us/press-room/photos-and-logos/

I do miss the icons a bit, because I tend to look for them when searching for a link (like permissions), but I think maybe we just need some other way of organizing them. Also, I'd like to hear what folks have to say about it.

**Comment by atoomic** [comment] 2022-07-26 21:27
This looks great and cannot wait to see it live.

Kind of sad to see the logo removed from the HomePage and replaced by some text.

Should not the `Search the CPAN` be used as a text placeholder in the search input text?

**Comment by oalders** [comment] 2022-07-26 21:52
> Kind of sad to see the logo removed from the HomePage and replaced by some text.

> Should not the Search the CPAN be used as a text placeholder in the search input text?

This would be worth looking at -- replacing the text with the logo and then moving "Search the CPAN" to placeholder text.

**Comment by dhogan8** [comment] 2022-07-26 22:15
Re: LiquidWeb - I agree that it is a little tough to see. I'm not sure if any of those options would be any better given the footer color itself is also a dark gray. It would be nice if we could get the text to be white like they have in their own footer, but I'm not sure if this is possible. Otherwise, we might have to make the footer white or a light gray.

Re: Icons - I can wait to hear back for more feedback.

Re: Logo / Search - Sure, I can put the logo back in if it is preferred. I initially removed it because when I looked at other sites, logos were mostly reserved for the header (e.g. top left) and usually engaging text or CTA about searching went above the search field. I will indeed move the "Search the CPAN" to the placeholder.

**Comment by oalders** [comment] 2022-07-26 22:33
> Otherwise, we might have to make the footer white or a light gray

Right. I don't think we need to worry about that for now. I'm happy to deploy it with the current colour and see if it needs more tweaks down the line.

**Comment by dhogan8** [comment] 2022-07-27 00:58
Does the updated work for the homepage?
<img width="1511" alt="Screen Shot 2022-07-26 at 8 56 13 PM" src="https://user-images.githubusercontent.com/52248962/181137578-f29aba95-e7c6-4309-bbb5-cb3fe70cbd1c.png">
<img width="295" alt="Screen Shot 2022-07-26 at 8 56 54 PM" src="https://user-images.githubusercontent.com/52248962/181137579-e0bcd597-c4c5-424f-8f3a-a5e997545d95.png">

**Comment by drclaw1394** [comment] 2022-07-27 02:15
General dark mode option/support would be nice. Switching between a dark dev environment and blindingly bright metacpan makes me squint!

**Comment by atoomic** [comment] 2022-07-27 04:13
I love the updated homepage, looks great!

**Comment by rwp0** [comment] 2022-07-27 04:59
Awesome! 👍🏻

**Comment by Ovid** [comment] 2022-07-28 09:39
Lovely!

**Comment by haarg** [comment] 2022-08-10 04:12
I'm using Firefox 104 on MacOS, and I'm seeing some issues with this currently:

  - Search box is highlighted on every page load. This is rather noticeable because the search box eats my normal keyboard combination for navigating back. So every new page prevents me from going back without extra effort. This is two bugs, but only one is related to the new design.
  - News page sidebar contains header links. This is confusing because if you click any of the options on the sidebar, all of the other options disappear. Feels like there has to be something better we could do here.
  - Pod Renderer (/pod2html) and Contributors (/about/contributors) need a top margin.
  - Home page is rendering wrong.
![Screenshot 2022-08-09 at 22-52-56 Search the CPAN - metacpan org](https://user-images.githubusercontent.com/50029/183809350-aa56e878-b160-4339-bc16-6bd5b16d1722.png)
  - Sidebar still needs some work. The things that used to be at the top of the left sidebar are probably the most important, but they are now pushed far down. I think starting with the author is fine, but the old top sidebar entries should probably be next. Contributors can be moved down and probably just converted to a link, dependencies can be converted to a link, "[Questions? Chat with us!" should be rephrased now that it isn't a banner. "Reverse dependencies"/"CPAN Testers List"/"Dependency graph" should be move lower or maybe merged with other sections.
  - Contents on a default page load feels awkward. Maybe it should always be pushed to a right sidebar? I'm not sure. 
![Screenshot 2022-08-09 at 23-05-17 Moo](https://user-images.githubusercontent.com/50029/183811223-4685f423-e311-49ac-9933-09d496785208.png)
  - The layout for the source view is too restricted. I'm not a huge fan of the max-width on the Pod content, but it's definitely wrong on the source view. Source is not wrapped, so the view should always be as wide as possible.
![Screenshot 2022-08-09 at 23-08-26 lib_Moo pm - metacpan org](https://user-images.githubusercontent.com/50029/183812241-5fb39912-02c7-4465-948b-f34e08a778c1.png)

More when I get time.

**Comment by dhogan8** [comment] 2022-08-12 00:58
Thanks for your feedback! I addressed a lot of this and will put it in a new commit on the PR https://github.com/metacpan/metacpan-web/pull/2710.
> * Search box is highlighted on every page load.

**Fixed: Removed the `autofocus` JS.**

> * News page sidebar contains header links. 

**Sorry, I'm not sure I understand this. Can you take a screenshot of the issue, please?**

> * Pod Renderer (/pod2html) and Contributors (/about/contributors) need a top margin. 

**Fixed: Added a margin, which is in line with other pages (`40px`).**

> * Home page is rendering wrong.

 **This is an issue on the staging site only. Olaf mentioned the issue here https://github.com/metacpan/metacpan-web/pull/2710#issuecomment-1211008364. Some of the JS isn't getting loaded. The local build renders properly though.**

> * Sidebar still needs some work.

**This is still a WIP. It would be helpful to have an ordered of items from top to bottom that you'd like to see. In general, I do see other areas of improvement and plan to do further updates in a separate PR. For example, I think we can potentially get rid of the author pic on any page that isn't the `/author/[authorname]` page. This might save some sidebar space**

> * Contents on a default page load feels awkward. Maybe it should always be pushed to a right sidebar?

**Fixed: Made it a fixed right sidebar, that you can still toggle the show and hide. But I removed the functionality to move it to the middle and to the right.**

> * The layout for the source view is too restricted. I'm not a huge fan of the max-width on the Pod content, but it's definitely wrong on the source view. Source is not wrapped, so the view should always be as wide as possible. 

**Fixed: I changed the max-width on the content class from `900px` to `1200px`, which is pretty wide.**

**Comment by dhogan8** [comment] 2022-08-17 00:03
Will the following sidebar work for now?
<img width="1511" alt="updated_sidebar_1" src="https://user-images.githubusercontent.com/52248962/185005464-74d50e1f-0ac2-45a9-9131-5e0fe605e1c9.png">
<img width="1511" alt="updated_sidebar_2" src="https://user-images.githubusercontent.com/52248962/185005467-3ceceebc-7df4-4de6-bf7c-ee0248941f50.png">

**Comment by thibaultduponchelle** [comment] 2022-08-21 13:22
Hello @dhogan8 

I'm really loving the redesign! 👍🏼 

Just to inform, I tested locally and I have this strange "non centered" homepage.

See sceenshot:

![not-centered-home](https://user-images.githubusercontent.com/580360/185792715-4aaf420b-0de6-4897-89c9-47916e931a9b.png)

I also noticed the load of website seems slower and it's maybe related to load of css files (?):
## Before
![css-before](https://user-images.githubusercontent.com/580360/185792752-72b34edf-3c6b-4a5e-a153-0744235ece77.png)

## New design
![css-after](https://user-images.githubusercontent.com/580360/185792765-3a210daa-7b47-4387-8c7e-6dbde634de0a.png)

Can't say more about what is causing this, maybe it's linked to my locat setup.

Apart from this, keep the good work!! Congratulation! 👏🏼

**Comment by dhogan8** [comment] 2022-08-21 14:23
@thibaultduponchelle Thanks for the feedback! Can you confirm whether all of the javascript assets are being loaded in your local environment? [Here](https://github.com/metacpan/metacpan-web/blob/dhogan8/update-layout/root/static/js/home.js) is the file that is responsible for adding a class on the `<body>` tag if it detects you are on the homepage. And then [here is the CSS](https://github.com/metacpan/metacpan-web/blob/dhogan8/update-layout/root/static/less/home.less#L5-L11) that styles the homepage so that you shouldn't be seeing that non-centered homepage.

**Comment by thibaultduponchelle** [comment] 2022-08-21 14:52
@dhogan8 Ok it works with `0.0.0.0:5001` instead `localhost:5001` 😃

**Comment by thibaultduponchelle** [comment] 2022-08-23 09:08
It's me or the [staging](https://web.stage.hc.metacpan.org/) seems to suffer the same? (despite being well listed [here](https://github.com/metacpan/metacpan-web/blob/dhogan8/update-layout/root/static/js/home.js#L7))

![stg](https://user-images.githubusercontent.com/580360/186118517-6de86b89-da46-4501-939d-9a8d4e72c488.png)

**Comment by thibaultduponchelle** [comment] 2022-08-23 09:13
Minor but I would prefer to have ithe "matrix" aligned with text:
![matrix](https://user-images.githubusercontent.com/580360/186120290-4731660f-0ebb-46da-8a35-9d1bb2f7e6dd.png)

**Comment by dhogan8** [comment] 2022-08-24 15:09
Thanks for catching that. I changed the CSS of that icon from `vertical-align: bottom` to `vertical-align: text-bottom`.

In general, I do understand that I personally don’t use this site as much (yet) so most of the changes I implemented don’t affect me getting used to a new style. I mostly tried to implement some common UI/UX principles. I’m not sure of the best way to improve the overall design of the site while also minimizing a new learning curve with the updated design.

The reason there is such a large gap is due to a couple reasons:
1. On most pages, the page content  has a `max-width: 1200px`. The wider the max-width, the less readable content becomes. The optimal character length for readability is about 75 characters. With a max-width of 1200px, the site’s character length sits at about 130 characters. As a result, there will be more white / empty space depending on a user’s screen size.
2. The content on the page is centered rather than left-aligned. Centering the page content prevents a user from tilting their head too much when reading (especially when on a larger desktop). I think it is fairly common to have content be centered.

If it helps, here are some other examples of where I grabbed inspiration from:
- https://developer.zendesk.com/documentation/developer-tools/getting-started/getting-a-trial-or-sponsored-account-for-development/
- https://developers.google.com/chat/how-tos/apps-script
- https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade
- https://dev.maxmind.com/minfraud/evaluate-a-transaction?lang=en

**Comment by djzort** [comment] 2022-09-07 04:03
This may be a larger change, but I find that the contents links box widget to be unintuitive and not all that helpful as I scroll down. Indeed, having the bus factor & testers numbers at my reference at all times is of far less use to me than navigational aids internal to the modules documentation.

On that basis my suggestion is that the page-internal links to the various headings be arranged in a similar way to the well known "readthedocs", so that navigation is prioritized over metadata.

![Screenshot_2022-09-06_20-54-43](https://user-images.githubusercontent.com/937277/188785745-5db9b83d-1ff2-46a8-98c2-0d3d43e655e0.png)
^ Links https://docs.readthedocs.io/en/stable/integrations.html

This is simply my opinion and I dont believe that metacpan is instrumented with heatmaps to show what people are clicking on or struggling to find. That would be a nice feature to add.

**Comment by dhogan8** [comment] 2022-09-07 13:51
@djzort As a temporary quick fix, would it be helpful if the Contents box were fixed on the right side of the page so that when you scroll down the page it still stays in view?
<img width="1206" alt="Screen Shot 2022-09-07 at 9 50 17 AM" src="https://user-images.githubusercontent.com/52248962/188895177-4159ae49-cc29-45fb-851f-2a71be03f4ce.png">

**Comment by haarg** [comment] 2022-09-07 15:11
As another data point, I would say 90% of my use of metacpan relates to looking at the sidebar data and links, and other metadata, rather than the documentation content itself.

**Comment by oalders** [comment] 2022-09-07 15:17
> As another data point, I would say 90% of my use of metacpan relates to looking at the sidebar data and links, and other metadata, rather than the documentation content itself.

I was thinking about this. We have two different (and overlapping) audiences. The CPAN developers probably lean heavily on the sidebar and CPAN consumers are probably more interested in the docs. The problem is that the development of the site is basically being driven by the CPAN authors. Non-PAUSE users are still second class citizens here.

I use the sidebar a lot and I like having that info easily available, but I can see how that may not be as helpful for a lot of other users.

**Comment by dhogan8** [comment] 2022-09-07 16:05
I do think it would be a better UX for people who are interested in the content to have a fixed TOC on the right side of the page. It seems like it would make it easier to jump around the content. I was worried about previously implementing this because I thought there was a concern about constraining the content width. But if this is not a concern, should I go ahead and make that change? 

This potential change would leave the left sidebar items untouched. I _think_ this would be a benefit to both CPAN developers (who value the left sidebar) and CPAN consumers (who value the content), but perhaps there might be a disadvantage to having a persistent TOC that I'm not aware of.

Alternatively, we could keep the branch as is and wait for feedback from other users.

**Comment by mohawk2** [comment] 2022-09-09 14:41
Are there any small parts of the changes here that can be pulled out and merged first?

**Comment by oalders** [comment] 2022-09-09 15:16
I think we can just merge the whole thing as soon as we figure out why the logins aren't working. If anyone can test out the GitHub login on the staging site and see if they also have issues, that would be helpful.

**Comment by thibaultduponchelle** [comment] 2022-09-09 15:43
I have an issue with GitHub login.

**Comment by oalders** [comment] 2022-09-09 15:54
Thanks @thibaultduponchelle!

**Comment by dhogan8** [comment] 2022-09-14 13:41
In order to accommodate for more sponsors in the footer, we had to switch the footer background color to something lighter. In order to add a little bit of contrast we made the header a darker color and added an inset shadow to the sidebar. Here are some updated screenshots:
<img width="1437" alt="home" src="https://user-images.githubusercontent.com/52248962/190169614-15b01fe8-2b64-40f1-81b0-a5a0e4f60805.png">
<img width="1437" alt="about" src="https://user-images.githubusercontent.com/52248962/190169622-d295b397-7b57-4aca-b348-da3d43f96edb.png">
<img width="1437" alt="pod" src="https://user-images.githubusercontent.com/52248962/190169625-2ac5a6c2-f0d2-4994-aaa0-a1e1fa58f6b9.png">
<img width="1437" alt="tools" src="https://user-images.githubusercontent.com/52248962/190169627-f18edda8-3691-4ca6-97e9-bab1208b7e62.png">
<img width="883" alt="sidebar" src="https://user-images.githubusercontent.com/52248962/190169634-cc369775-2f41-4681-8f72-80709acd353a.png">
<img width="877" alt="search" src="https://user-images.githubusercontent.com/52248962/190169636-ca961c60-9e84-402c-9398-d5a2bc4cc7b5.png">

**Comment by oalders** [comment] 2022-09-14 14:07
ping @freyfogle ^^

**Comment by freyfogle** [comment] 2022-09-14 17:36
looks great, very nice

**Closed** 2022-10-03 18:19 UTC
Labels: type:Feature
