### ISSUE TITLE
404 on "perl"

### ISSUE THREAD

**Issue by plicease** [metacpan/metacpan-web#1960] opened 2017-08-09 11:17 UTC
This URL:

https://metacpan.org/release/perl

gives me a 404 error.  There is a link to this obscure distribution from this page:

https://metacpan.org/pod/strict

and the widget that lets me select old versions of Perl from that page doesn't seem to be working either.

**Comment by mickeyn** [comment] 2017-08-09 17:28
This is now fixed.

The problem is not specific to "perl", it has to do with cache purging upon indexing.
we'll sort that out.

**Comment by jscook** [comment] 2017-08-13 02:46
I noticed this with 'ack' today and I imagine it is related.

**Closed** 2017-11-16 21:41 UTC
