### ISSUE TITLE
SCO redirect regression on version-less distpaths

### ISSUE THREAD

**Issue by ribasushi** [metacpan/metacpan-web#1951] opened 2017-07-21 11:08 UTC
This used to work, but looks like a specific route got dropped recently. It is possible this might need to be addressed in the `mcpan.org` redirector instead.

To reproduce:
* Start from e.g.: http://search.cpan.org/~haarg/Moo/
* Perform `s/search\./m/`: http://mcpan.org/~haarg/Moo/
* That redirects to a 404 of: https://metacpan.org/release/HAARG/Moo

As a bonus at the bottom of the 404 page in the last step, there is text like `Search the CPAN for IO::Async::Future=HASH(0xa47c0d0)`

Cheers

**Comment by haarg** [comment] 2017-07-21 12:55
I'm pretty certain that this is not a regression.  We have never had an endpoint on metacpan itself for and author with an unversioned dist.  And since the redirector is just a set of regexes, it can't work around that.  This is something we intend to fix with a new redirector, which will have much more comprehensive coverage of possible search.cpan.org URLs.

Going to close this since it isn't a regression, and is already planned as part of other tickets.

I have a fix for the search text issue which I'll push soon.

**Closed by haarg** 2017-07-21 12:55 UTC
