### ISSUE TITLE
recent.rss Changes aren't always present even when module page changes are

### ISSUE THREAD

**Issue by wolfsage** [metacpan/metacpan-web#2856] opened 2023-01-09 17:35 UTC
**Describe the bug**

If you compare https://metacpan.org/recent.rss?f=l with, say, https://metacpan.org/release/KARJALA/BoardStreams-v0.0.29,
you'll notice the RSS has this:
```
    <item>
      <title>BoardStreams-v0.0.29</title>
      <link>https://metacpan.org/release/KARJALA/BoardStreams-v0.0.29</link>
      <author>KARJALA</author>
      <guid isPermaLink="true">https://metacpan.org/release/KARJALA/BoardStreams-v0.0.29</guid>
      <pubDate>Mon, 09 Jan 2023 16:53:34 GMT</pubDate>
      <description>An easy way to use WebSockets on the browser and on the server</description>
    </item>
```

There's no changes listed in the RSS inside the description block. But if you go to the release page you see them properly parsed out:
```
 Changes for version v0.0.29 - 2023-01-09

    complete rewrite, completely breaking backwards compatibility

```

**Expected behavior**

I would expect the RSS to include these changes like it does for other releases. For example:
```
    <item>
      <title>FASTX-Reader-1.8.1</title>
      <link>https://metacpan.org/release/PROCH/FASTX-Reader-1.8.1</link>
      <author>PROCH</author>
      <guid isPermaLink="true">https://metacpan.org/release/PROCH/FASTX-Reader-1.8.1</guid>
      <pubDate>Mon, 09 Jan 2023 15:25:10 GMT</pubDate>
      <description>&lt;p&gt;A simple module to parse FASTA and FASTQ files, supporting compressed files and paired-ends.&lt;/p&gt;&lt;p&gt;Changes for 1.8.1 - 2023-01-09&lt;/p&gt;&lt;ul&gt;&l>
&lt;li&gt;Update POD documentation&lt;/li&gt;
&lt;/ul&gt;</description>
    </item>
```

**Additional context**

Taking a quick look at the code, maybe this is because the Feed generation does (MetaCPAN/Web/Controller/Feed.pm's recent() ):
```
        my $changes
            = $c->model('API::Changes')
            ->by_releases( [ map { [ $_->{author}, $_->{name} ] } @batch ] )

```
Whereas the distribution info page does ( MetaCPAN/Web/Model/ReleaseInfo.pm 's _release_data() ):
```
                changes => $self->_changes->release_changes(
                    [ $author, $release ],
                    include_dev => 1
                ),
```

... assuming I found the right bits of code.

No idea!

Thanks :heart:

**Comment by haarg** [comment] 2023-01-09 18:29
The problem is that the `by_releases` method doesn't understand `v` prefixes in the version on release names.

Fixed by #2857, which rewrites the entire method to work more reasonably.

**Closed** 2023-01-11 16:56 UTC
Labels: type:Bug
