### ISSUE TITLE
Add ability to sort results by various criteria, including ++-es

### ISSUE THREAD

**Issue by genehack** [metacpan/metacpan-web#1923] opened 2017-06-17 03:27 UTC
Per conversation in irc.perl.org#metacpan 

```
15:22:30 <genehack> is there a way, using metacpan.org, to sort results by ++-ing? 
15:27:21 <Grinnz> https://metacpan.org/favorite/leaderboard
15:27:37 <Grinnz> don't know if there's any way to get a different view of that
15:27:42 <Grinnz> probably via the api there is
15:29:23 <genehack> Grinnz: no, what i mean is, say i search for 'template' 
15:29:34 <genehack> _within those results_ can i get the more ++'d ones at the top 
15:29:46 <Grinnz> don't think there's any way to do that in the frontend
15:30:03 <genehack> do you know off hand if there's a ticket? 
15:30:11 <genehack> if not, i'll make one 
15:31:06 <genehack> (context: i searched 'template', and text::xslate isn't in the first few hundred results, which seems pretty wrong. pretty sure if i sorted by ++-es it would be on the first page or two 
15:31:08 <genehack> )
15:31:13 <Grinnz> https://github.com/metacpan/metacpan-web/issues/471 looks like it was closed a while ago though
15:31:49 <genehack> yeah, i think i'm gonna make a new ticket and see what happens. 
15:33:01 <genehack> or maybe not, since the issue template tells me to GTFO unless i'm gonna code it myself 8^/ 
15:34:55 <Grinnz> oalders / ranguard / mickey: is that issue template still useful for you guys? istr haarg said it wasn't for him
18:41:20 <oalders> Grinnz, genehack: actually, now is a good time to create a ticket for that.  with the search code now ported to the API we can look at some arbitrary boost parameters.  
```

**Comment by haarg** [comment] 2018-10-15 14:47
Closing as dupe of #2054.

**Closed by haarg** 2018-10-15 14:47 UTC
