### ISSUE TITLE
Unable to connect to PAUSE

### ISSUE THREAD

**Issue by dag-erling** [metacpan/metacpan-web#2500] opened 2021-05-13 20:03 UTC
Logging in to MetaCPAN with Github and trying to connect to PAUSE; nothing happens. I just get redirected to the front page after typing in my PAUSE ID (DES) and clicking “Log In”. I have verified that my CPAN email works. I'm aware of the [FAQ](https://metacpan.org/about/faq#whycantilinkmypauseaccount) and have tried what it suggests.

**Comment by AWADHAMBIKA** [comment] 2021-05-21 10:02
Same here for me. Unable to connect my PAUSE account

**Comment by ownlifeful** [comment] 2021-06-14 01:35
Same here. Cannot connect my PAUSE account ( ASHWIN ).

**Comment by oalders** [comment] 2021-06-14 02:05
Sorry for this issue. It's really annoying. I should have some free time at the end of this week to devote to authentication issues.

**Comment by oalders** [comment] 2021-06-18 20:54
I think the issue is here: https://github.com/metacpan/metacpan-api/blob/3f3c61544a4f4d9d9b31ad4b185b5e92d02fadcb/lib/MetaCPAN/Server/Controller/Login/PAUSE.pm#L20-L23

We're caching a code on disk and hoping that Fastly will route consecutive requests to the same back end server.

**Comment by oalders** [comment] 2021-06-18 20:56
This looks to be the only place we're using `CHI` in this repo, so when we refactor, we should be able to drop this dependency.

**Comment by oalders** [comment] 2021-06-18 21:00
@mickeyn should we just move this code/session id to the `User` type and get rid of the cache? We're already using that type for access tokens.

**Comment by FractalBoy** [comment] 2021-06-30 02:57
I am also having this issue.

**Comment by oalders** [comment] 2021-07-01 14:35
@FractalBoy what is your PAUSE id?

**Comment by oalders** [comment] 2021-07-01 14:36
@AWADHAMBIKA what is your PAUSE id?

**Comment by ownlifeful** [comment] 2021-07-01 14:38
My PAUSE id is ASHWIN

Thanks,

**Comment by FractalBoy** [comment] 2021-07-01 14:44
MREISNER

**Comment by esabol** [comment] 2021-07-01 16:04
I'm having this problem too. My PAUSE id is ESABOL, same as my GitHub id.

**Comment by AWADHAMBIKA** [comment] 2021-07-02 00:50
Hi @oalders my PAUSE ID is ROCKETDB

**Comment by oalders** [comment] 2021-07-10 16:00
A change has now been made to force PAUSE logins to the same app server. Could one or two people on this ticket try again?

**Comment by FractalBoy** [comment] 2021-07-10 16:07
@oalders Yes, that seems to have worked.

**Comment by esabol** [comment] 2021-07-10 16:19
@oalders Not working for me, but it is different. It says, "An email has been sent to the email address associated with the PAUSE account. Please check your inbox and verify your account by visiting the link in the mail." But I haven't received any emails from MetaCPAN after several attempts. I checked that emailing my PAUSE public email address correctly forwards to my secret email address as configured in PAUSE.

**Comment by dag-erling** [comment] 2021-07-10 19:41
Worked for me, but the UX was not the best:

1. I clicked the link in the email and was redirected to https://fastapi.metacpan.org/user which gives me a json object with some basics about my account.
1. I clicked it again and got an empty json document (no redirect).
1. I then reloaded the metacpan Identities page, which now shows me as connected to PAUSE.
1. I clicked the button to connect to GitHub and was redirected to the same URL as previously, which returned the same json object but now with a huge `github` section.
1. Returning to the Identities page showed that my account was now connected to GitHub.
1. I clicked the button to connect to Twitter. I got the Twitter app authorization dialog and approved the request. It redirected me to https://fastapi.metacpan.org/login/twitter with an oauth token, but that just shows a “Please come back later” error page.
1. I tried Twitter a second time with the same result. The Identities page still shows my account as not connected to Twitter.
1. Finally, I tried the Google button, which seemed to work fine (I think the dialog closed once I'd authorized the connection).
1. The `identities` section in the json object now contains `pause`, `github`, and `google` sections, but no` twitter` section.

BTW, it would be nice if the json object was sorted so one could more easily compare the results of repeated API calls.

**Comment by oalders** [comment] 2021-07-11 01:27
@dag-erling you should actually never see the JSON object, so that in itself is a bug. I have a theory on that one, but it has popped up occasionally over the years and been really hard to reproduce. Not sure what's going on with Twitter. ☹️

**Comment by oalders** [comment] 2021-07-11 01:29
@esabol the issue with your account now is:

> <esabol@cpan.org>: host pb-mx9.pobox.com[64.147.108.50] said: 550 5.1.1
    <esabol@cpan.org>: Recipient address rejected: User unknown (in reply to
    RCPT TO command)

**Comment by oalders** [comment] 2021-07-11 01:30
@neilb do you know why that error might occur with esabol@cpan.org?

**Comment by esabol** [comment] 2021-07-11 02:06
> @esabol the issue with your account now is:
> 
> > [esabol@cpan.org](mailto:esabol@cpan.org): host pb-mx9.pobox.com[64.147.108.50] said: 550 5.1.1
> > [esabol@cpan.org](mailto:esabol@cpan.org): Recipient address rejected: User unknown (in reply to
> > RCPT TO command)

Weird. I just tested sending an email to esabol@cpan.org, and I received the email at my gmail account. So that seems to be working now. But shouldn't the email be sent to esabol@pause.org when you're trying to connect one's PAUSE account to one's MetaCPAN account? The message that's displayed says, "An email has been sent to the email address associated with the PAUSE account." So why is it being sent to @cpan.org?

Anyway, ~10 hours later and without making any changes to my accounts, I tried to connect my MetaCPAN account to my PAUSE account, and it worked! This time, I received the email, and, just like @dag-erling reported above, I clicked on the link in email and it took me to https://fastapi.metacpan.org/user and showed a JSON response. Regardless, the MetaCPAN Identities page shows my PAUSE account is connected. So thank you!

**Comment by Grinnz** [comment] 2021-07-11 02:26
There's no pause.org emails (Perl does not even own pause.org).

**Comment by esabol** [comment] 2021-07-11 02:37
> There's no pause.org emails (Perl does not even own pause.org).

It seems weird that I can email esabol@pause.org then.

**Comment by oalders** [comment] 2021-07-11 15:27
I don't even see MX records for pause.org. :)

**Comment by oalders** [comment] 2021-07-11 15:28
Is there anyone left on this ticket who still cannot connect their PAUSE account?

**Comment by ownlifeful** [comment] 2021-07-11 15:41
I was able to connect my PAUSE account successfully as well.

Thanks,

**Comment by AWADHAMBIKA** [comment] 2021-07-12 04:53
Hi @oalders I got a verification email from CPAN and when I click the same it shows "{}" but my PAUSE account is still not linked and keep getting the verification email.
I am sorry but looks like not wokring from me.

**Comment by oalders** [comment] 2021-07-12 17:48
@AWADHAMBIKA can you try logging out and back in and then trying again?

**Comment by AWADHAMBIKA** [comment] 2021-07-13 04:13
I think I got the issue. Hope this helps others:
I was directly clicking the activation link sent over email and it was going through my company firewall i.e. Outlook security check which I guess strips something and hence I was getting "{}" as response.
Later I copy and pasted the activation link directly in the browser and then response was different with the detailed JSON containing my ID name and other details and after that my PAUSE account was connected successfully.

Thanks anyways @oalders  :)

**Comment by oalders** [comment] 2021-07-13 13:44
Thanks @AWADHAMBIKA! I think we can close this ticket now. If anyone is still having issues, feel free to open a new issue.

**Closed by oalders** 2021-07-13 13:44 UTC
Labels: group:Accounts
