### ISSUE TITLE
color config in apps like "podview"

### ISSUE THREAD

**Issue by Astara** [metacpan/metacpan-web#2204] opened 2019-07-23 09:19 UTC
Is there a config file to change the default color?  Black on white is good for reflective light (like light on a book), but for emissive surfaces, it's like looking into a bright light with little shadows over it.  Lots of glare and hard on the eyes.

Eventually when screens get brighter to support more than 255 levels of brightness they will get too bright to stare at have to change -- some UI's are already changing and providing a dark background, some only provide a dark background -- so hopefully there is a an easy config file ... tried changing the .Xdefaults file, but that didn't seem to work -- may have had the name wrong though...

Meanwhile, I guess I stick with a tty interface, since most grey on white text is hard to read for people with light sensitive eyes.  :-(

**Comment by oalders** [comment] 2019-08-31 00:43
On Chrome you can do this with https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by haarg** [comment] 2019-10-08 15:01
Dupe of #2182.

**Closed by haarg** 2019-10-08 15:01 UTC
