### ISSUE TITLE
Deprecation banner on module which doesn't appear to be deprecated

### ISSUE THREAD

**Issue by bigpreshkt** [metacpan/metacpan-web#2438] opened 2021-02-22 17:16 UTC
I see that #2436 has started showing deprecation banners.

I see one for, e.g. https://metacpan.org/pod/CHI

However, I don't see anything to suggest that module is deprecated, and if I ask the API:

```
[davidp@columbia:~]$ jq .deprecated <(curl -s https://fastapi.metacpan.org/v1/release/CHI)
"false"
```

Similarly, no sign that it should be deprecated at https://explorer.metacpan.org/?url=/module/JSWARTZ/CHI-0.60/lib%2FCHI.pm

Am I missing something obvious, or is this displaying the banner wrongly?

**Comment by bleargh45** [comment] 2021-02-22 17:55
That _does_ appear to be incorrect; let me go take a look at that for you right now.

**Comment by bleargh45** [comment] 2021-02-23 04:56
Now seeing what the discrepancy was that caused this to occur...

When using the local `metacpan-docker` setup to do development with, the `deprecated` field is properly cast as a Boolean, and returns `false`.  The Production API, however, returns it as a string value, `"false"`:

```
$ curl --silent http://localhost:5000/module/CHI        | jq .deprecated
false

$ curl --silent http://fastapi.metacpan.org/module/CHI  | jq .deprecated
"false"
```

**Comment by bleargh45** [comment] 2021-02-23 05:22
And, more frustratingly, it also appears that the boolean-ness of the values are not consistent across the API Index:

```
$ curl --silent http://fastapi.metacpan.org/release/Alien-Prototype-Carousel  | jq .deprecated
true

$ curl --silent http://fastapi.metacpan.org/release/CHI  | jq .deprecated
"false"
```

```
$ curl --silent http://fastapi.metacpan.org/module/Dist::Zilla::Plugin::EOLTests | jq .deprecated
true

$ curl --silent http://fastapi.metacpan.org/module/Dist::Zilla::Plugin::Test::EOL | jq .deprecated
"false"
```

So... for the moment, simplest approach looks like checking not just for the 1/0-ness of the Bool, but also for "true/false" (as strings).  At least, until we can determine what's up with the underlying index, and can figure out how to address that.

**Comment by oalders** [comment] 2021-02-23 22:24
@mickeyn any idea what's going on with the booleans?

**Comment by bleargh45** [comment] 2021-02-23 23:38
If I had to wager a guess... I _think_ what may have happened is that when the `deprecated` field was added to the index and backfilled, the backfill accidentally got done with a string value; when I've checked various releases/distributions, it _feels_ like "more recent Releases got a Boolean, older ones got a String".

```
$ curl --silent http://fastapi.metacpan.org/release/GTERMARS/Data-FormValidator-EmailValid-0.05 | jq .release.deprecated
"false"

$ curl --silent http://fastapi.metacpan.org/release/GTERMARS/Data-FormValidator-EmailValid-0.06 | jq .release.deprecated
false
```

(do note, though, that there *are* several _years_ between those two releases)

**Comment by oalders** [comment] 2021-02-23 23:53
Ah! I just re-indexed 0.05 and it looks to no longer return the string.

**Comment by oalders** [comment] 2021-02-23 23:53
It might make sense just to re-index everything again. @mickeyn what do you think?

**Comment by bleargh45** [comment] 2021-02-24 00:04
Reading through the old ElasticSearch docs, I see reference to an "Update by Query API", which _sounds_ like it could be useful (to someone who could craft a better ES search than I).  Sounds like it can take records that match a given query, and then reindex them to pick up new fields. Example provided in the docs is a new field was added to the index, and the existing docs need to be reindexed to pick it up.

_Unsure_ if that's useful here, but figured I'd throw it out there just in case.

**Comment by oalders** [comment] 2021-02-24 00:14
I think that API is probably helpful for indexing plain documents, but a lot of what we're doing is parsing the documents ourselves and setting fields based on that, so it won't cover all of our needs.

**Comment by mickeyn** [comment] 2021-02-24 07:41
@oalders mass reindexing older versions is always tricky because it's done against current CPAN index and permissions files it will probably cause some authorization issues as we've seen before.

The boolean issue is probably a Perl problem (not that ES issue in this old version is out of the question). 
We have boolean fields set in the mapping and we rely on Bool type of the Moose attributes where we only set 1 / 0 - something to dig deeper into (maybe we should be using a different type? set different values?).

**Comment by bleargh45** [comment] 2021-02-25 04:29
If I've found the right chunk of code, then I'm left to question if we're even using the mapping... down in [metacpan/metacpan-api/lib/MetaCPAN/Document/Release/Set.pm#L55](https://github.com/metacpan/metacpan-api/blob/master/lib/MetaCPAN/Document/Release/Set.pm#L55) it calls `$self->filter(...)->sort(...)->raw->first`.

That `->raw` part is what caught my eye; is that not just returning the raw hash-ref of data from ES, as opposed to running it through the mapping and/or object transformation first?

Unfortunately, I'm somewhat hindered here as the `metacpan-docker` setup doesn't generate this same "string `false`", thus making it harder for me to be of assistance in helping sort out where the proper fix for this lies.

**Comment by mohawk2** [comment] 2021-02-25 09:38
I know this isn't going to be what's fun to hear (or action), but I fear that figuring out how to repro the string-false is essential to correctly addressing this.

**Comment by oalders** [comment] 2021-02-25 14:10
My first thought was that it's an issue with our boolean handling in Perl. Having said that, if we can't reproduce the problem with the Docker setup and if the following is always correct after having been re-indexed

```
$ curl --silent http://fastapi.metacpan.org/release/GTERMARS/Data-FormValidator-EmailValid-0.05 | jq .release.deprecated
```

then I'm inclined to think maybe the bug was in our indexing process at some point or just the initial backfill, as @bleargh45 has suggested.

**Comment by oalders** [comment] 2021-02-25 14:11
I guess we could just check that field for everything in the index and see if there's a pattern. :)

**Comment by bleargh45** [comment] 2021-02-25 17:07
**IF** it's related to the backfill, one possible strategy could be to go back and query "releases just prior to the `deprecated` field being added" (and thus were populated with the backfill), and compare that to "releases after the `deprecated` field being added" (to confirm that post-release, everything seemed sane).  Might help cut down on how much needs to be queried.

**Comment by bleargh45** [comment] 2021-02-25 18:06
Here's a dumb little script I whipped up to take a given Distribution and then go back through all of the known releases and see whether we get `false` or `"false"` returned back from the MetaCPAN API.

```
#!/usr/bin/perl

use strict;
use warnings;
use JSON::XS qw(decode_json);

# What Distribution are we querying?
my $dist = shift @ARGV;
die "No Distribution given to query\n" unless $dist;

# Get a list of all of the released versions of that Dist, and their dates
my $json = qx{ curl --silent http://fastapi.metacpan.org/release/versions/$dist };
my $data = decode_json($json);

# Iterate over all of those releases, and see if there's a point where we went
# from "false" to false.
foreach my $rel (@{ $data->{releases} }) {
  my $date   = $rel->{date};
  my $author = $rel->{author};
  my $name   = $rel->{name};
  my $res = qx{ curl --silent http://fastapi.metacpan.org/release/$author/$name | jq .release.deprecated };
  chomp $res;
  printf "%10s\t%20s\t%s\n", $res, $date, $name;
}
```

Isn't fancy, but works.

With that, I'm leaning towards this having been an issue with the initial backfill; when querying both `Mojolicious` and `Test2-Suite` (two dists that know have had many releases over the years), the inflection point from `false` to `"false"` sits around Jan/Feb 2018... the point at which this `deprecated` field was added to the index.

**Comment by oalders** [comment] 2021-02-25 18:18
Excellent. I suppose we could also look at running a script which only aims to fix up this one field rather than re-indexing everything. That way we don't have older releases which suddenly show up as "unauthorized" because the permissions have changed in the meantime.

**Comment by bleargh45** [comment] 2021-02-25 19:01
Fixing up **just** the one field (as opposed to a full re-index) does sound like a better approach.  Less churn, less chance of accidentally monkeying something up.

**Comment by oalders** [comment] 2021-02-25 19:11
It wouldn't even need to be a complicated search. We'd just need to get all release documents before some date and then fix up the ones that need it.

**Comment by bleargh45** [comment] 2021-02-25 19:17
That's actually what led me down the path to looking at the "Update by Query" API that ElasticSearch has, to see if there was some way to do the ES equivalent of `UPDATE index SET deprecated=false WHERE deprecated='false'`

Effectively... "search for the bad ones, then update them with the proper `false`"

**Comment by oalders** [comment] 2021-02-25 19:34
Right. In this case I think we *can* use that kind of API, since we don't need to run the indexer. So, I was too quick to dismiss "update by query". I'm not sure if that's in 2.4 but I think there is at least something similar. Hard to find docs on that version of Elasticsearch.

**Comment by bleargh45** [comment] 2021-02-25 19:44
Here's what I had found previously, _in case_ it turns out to be helpful/useful:

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-update-by-query.html

**Comment by oalders** [comment] 2021-02-25 20:00
@bleargh45 is this something that you'd like to write?

**Comment by bleargh45** [comment] 2021-02-25 20:10
When I bumped into this the other day, I scratched out the following as notes for myself.

**NO IDEA** if this will actually work, _but_ I think it would at least help point us in the right direction.

```
# This *sounds like* it should work?
#
# According to the ES-2.4 docs, issuing an update in this form should
# trigger the Index to refresh/recalculate itself, as is similar to the
# example they provide in the Docs for "Picking up a new property".
#
# And, it'll abort on conflicts, which may mean that we have to run it
# more than once, until there are none left.
POST /<index>/_update_by_query?refresh=true&pretty=true
  {
    "conflicts": "proceed",
    "query": {
      "term": {
        "deprecated": "false"
      }
    }
  }


# Alternatively... a query like this should find all of the affected
# documents, from which we can then issue individual Updates to each
# one, to set it as a "boolean" and not a "string".
POST /<index>/_search
  {
    "query": {
      "term": {
        "deprecated": "false"
      }
    }
  }
POST /<index>/_update/<id>?refresh=true&pretty=true
  {
    "doc": {
      "deprecated": false
    }
  }
```

I'm not an ES wizard by any means, and the above is essentially "_looked_ sane, based on what I was seeing in the ES docs", but I honestly have _no idea_ if the above queries/updates are actually syntactically valid or not.

**Comment by oalders** [comment] 2021-02-25 21:03
@mickeyn what do you think? ^^

**Comment by haarg** [comment] 2021-02-25 22:22
I'm working on fixing the data.

**Comment by bleargh45** [comment] 2021-02-25 22:48
Appreciated!

**Comment by mickeyn** [comment] 2021-02-26 05:40
I see @haarg is working on it - great!!!

quick check shows me that a query using curl+jq doesn't really give me different results if I quote the boolean values, so I'm a bit confused:

```
>> curl -s -XPOST 'https://fastapi.metacpan.org/release/_search?size=0' -d'{"query":{"term":{"deprecated":"false"}}}' | jq .hits.total
343949

>> curl -s -XPOST 'https://fastapi.metacpan.org/release/_search?size=0' -d'{"query":{"term":{"deprecated":false}}}' | jq .hits.total
343949

>> curl -s -XPOST 'https://fastapi.metacpan.org/release/_search?size=0' -d'{"query":{"term":{"deprecated":true}}}' | jq .hits.total
508

mickey @ fireball : ~ :  : master
>> curl -s -XPOST 'https://fastapi.metacpan.org/release/_search?size=0' -d'{"query":{"term":{"deprecated":"true"}}}' | jq .hits.total
508
```

Am I doing something wrong?

**Comment by haarg** [comment] 2021-02-26 06:12
Elasticsearch itself treats the values as equivalent.

**Comment by mickeyn** [comment] 2021-02-26 06:31
Is it documented? I thought of trying it with Sense to see that, but it seems like a hassle to set it up.

**Comment by haarg** [comment] 2021-02-27 04:56
I believe all of the data should be fixed now, although it's hard to test due to the issue @mickeyn showed.

**Comment by bleargh45** [comment] 2021-02-27 17:36
Can confirm, that using the [dummy script I whipped up earlier](https://github.com/metacpan/metacpan-web/issues/2438#issuecomment-786096126), as well as the [curl commands](https://github.com/metacpan/metacpan-web/issues/2438#issuecomment-784609343) noted above, that I now **only** receive back proper boolean `false` responses from the API, and **no longer** receive any string `"false"` responses.

Woo-hoo!  **Thank you** @haarg!

With that appearing to be fixed, at some point over the weekend, I'll craft a PR to re-enable the notification display.  I'll also re-examine the one other instance in the code where I've found a hack to try to deal with boolean string weirdness, and will see if that is a hack that still needs to be preserved or whether we can now drop that.

**Comment by haarg** [comment] 2021-02-27 17:42
For reference, I created the script `set_deprecated.groovy` on our servers in the appropriate locations, with the content
```
ctx._source.deprecated = deprecated;
```
Then ran the commands:
```
curl -XPOST 'http://localhost:9200/cpan_v1_01/release/_update_by_query?pretty&conflicts=proceed&wait_for_completion=false' -d '{
  "script": {
    "file" : "set_deprecated", "params" : { "deprecated" : true }
  },
  "query": {
    "term" : {
      "deprecated" : "true"
    }
  }
}'
curl -XPOST 'http://localhost:9200/cpan_v1_01/release/_update_by_query?pretty&conflicts=proceed&wait_for_completion=false' -d '{
  "script": {
    "file" : "set_deprecated", "params" : { "deprecated" : false }
  },
  "query": {
    "term" : {
      "deprecated" : "false"
    }
  }
}'
curl -XPOST 'http://localhost:9200/cpan_v1_01/file/_update_by_query?pretty&conflicts=proceed&wait_for_completion=false' -d '{
  "script": {
    "file" : "set_deprecated", "params" : { "deprecated" : true }
  },
  "query": {
    "term" : {
      "deprecated" : "true"
    }
  }
}'
curl -XPOST 'http://localhost:9200/cpan_v1_01/file/_update_by_query?pretty&conflicts=proceed&wait_for_completion=false' -d '{
  "script": {
    "file" : "set_deprecated", "params" : { "deprecated" : false }
  },
  "query": {
    "term" : {
      "deprecated" : "false"
    }
  }
}'
```

**Comment by bleargh45** [comment] 2021-02-28 01:11
Ok... I can confirm that the following pages look **correct**:

* https://metacpan.org/release/CHI
  * no longer shows "Deprecated" (which was the bug noted back in #2438)
* https://metacpan.org/release/Alien-IE7
  * shows "Deprecated" for the Release, and **all** files contained within it
* https://metacpan.org/release/Dist-Zilla-Plugin-Test-EOL
  * does _not_ show "Deprecated" notice on the Distribution, but _does_ show it on the one deprecated module that is present within the Distribution
* https://metacpan.org/release/Acme-Hello
  * showing the pre-existing `NEEDHELP` notification, identifying to me that the Permissions-based notifications are continuing to work properly

**Comment by bleargh45** [comment] 2021-02-28 17:57
I believe that this ticket should now be resolved... could someone do one last confirm and then close it out?

**Comment by oalders** [comment] 2021-03-01 14:12
Looks great! This is a very helpful improvement. 🎉

**Closed by oalders** 2021-03-01 14:12 UTC
