### ISSUE TITLE
Recent page appears stuck

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#2992] opened 2024-02-19 09:32 UTC
**Describe the bug**
The "Recent" page at https://metacpan.org/recent is not showing any new releases since Friday. I know there has been at least one as I made one yesterday.

**To Reproduce**
1. Go to https://metacpan.org/recent
2. See that there are no new releases since Friday when ordinarily there are maybe 20 per day.

**Expected behavior**
I expect to see the releases made since Friday.

**Screenshots**
![image](https://github.com/metacpan/metacpan-web/assets/4331674/144f91ee-917a-4b30-b0e3-a474d684d17b)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Pale Moon
 - Version 33.0.0 (64-bit)

**Comment by openstrike** [comment] 2024-02-19 10:26
Looking around, it seems that this is a symptom of a wider problem. My dist released yesterday (Password-Policy-Rule-Pwned-0.02_02.tar.gz) is not recorded anywhere within MetaCPAN AFAICS. :-/

**Comment by eserte** [comment] 2024-02-19 18:33
PAUSE also had problems accepting new uploads on Friday and Saturday, but this seems to be fixed since Sunday.

**Comment by robrwo** [comment] 2024-02-20 10:48
It would be helpful for users if a short alert about the issues with PAUSE were added to the page.

**Comment by sanko** [comment] 2024-02-20 19:45
MetaCPAN has fully tipped over.

I was checking to see if it caught up to an upload I made after PAUSE came back online and the recent page now returns an 'Internal Server Error' instead. Search (such as https://metacpan.org/search?q=perl) no longer returns results and even direct links like https://metacpan.org/pod/Task::Kensho are failing.

**Comment by eserte** [comment] 2024-03-27 09:04
I did not see any obvious problems anymore in the last weeks.

@oalders: Was the root cause found and fixed?

**Comment by oalders** [comment] 2024-03-27 14:47
> Was the root cause found and fixed?

@eserte, there have been a couple of things going on. PAUSE had some issues that were taken care of. I don't know if they'll pop up again, but it looks like we're getting closer to being able to deploy PAUSE somewhere else.

MetaCPAN had some issues with the Elasticsearch cluster and those were taken care of at the time, but I can't rule out further Elasticsearch issues, based on our current setup. I do hope we'll be able to improve that soon, though. We will see what happens in Lisbon.

At any rate, I think we can close this particular issue now. Thanks, everyone!

**Comment by eserte** [comment] 2024-04-18 09:33
It seems it's happening again:
![grafik](https://github.com/metacpan/metacpan-web/assets/65852/2b241b0b-4128-4d2b-b73c-7d68ed14b9c4)

**Comment by oalders** [comment] 2024-04-18 19:41
Had to fix a bunch of disk errors, which I assume will happen again in the near future. We have a plan to move off the disk, though. Thanks for reporting @eserte. The indexer is catching up now.

**Closed by oalders** 2024-04-18 19:41 UTC
Labels: type:Bug
