### ISSUE TITLE
The sign-in page should go back to where it came from

### ISSUE THREAD

**Issue by benkasminbullock** [metacpan/metacpan-web#1848] opened 2017-01-21 02:36 UTC
If I sign in on a page, like

https://metacpan.org/author/BKB

then after I have signed in, I am sent to

https://metacpan.org/

rather than the page I came from.

This behaviour is rather disconcerting and unexpected; I'm not sure whether this is a feature request or not, but going back to the original page where I clicked "sign in" seems the obvious expected behaviour, and being sent to the top page seems quite odd.

**Comment by oalders** [comment] 2017-01-21 16:06
Would be nice to have.  I wouldn't call it a bug.  I guess it's mostly an 80% solution that we currently have.

**Comment by vhamon** [comment] 2017-02-01 15:05
Actually, I'm trying to signin with github and I am redirected directly to https://metacpan.org/.
While Signin with Facebook works and send me to Facebook. Maybe I got wrong, but I don't know how to sign up for first time. Google oauth gives error 400, should I create a new issue ?

**Comment by benkasminbullock** [comment] 2017-02-01 22:31
On 2 February 2017 at 00:05, Valentin Hamon <notifications@github.com>
wrote:

> Actually, I'm trying to signin with github and I am redirected directly to
> https://metacpan.org/.
>
That problem is not related to this bug report.

**Comment by haarg** [comment] 2018-06-21 04:39
Dupe of #1204

**Closed by haarg** 2018-06-21 04:39 UTC
Labels: type:Feature
