### ISSUE TITLE
-1 non-PAUSE users

### ISSUE THREAD

**Issue by benkasminbullock** [metacpan/metacpan-web#1974] opened 2017-10-06 01:32 UTC
Please see

https://metacpan.org/pod/Regexp::IPv6

The number of pluses is given as 1, yet two pause users and -1 non-pause users have done that.

![minus-one-users](https://user-images.githubusercontent.com/102005/31259445-987d5372-aa81-11e7-9c5c-b3bcafb19bc0.png)

**Comment by oalders** [comment] 2017-11-16 21:38
Duplicate of #1964

**Comment by oalders** [comment] 2017-11-16 21:39
Thanks for reporting this @benkasminbullock!

**Closed by oalders** 2017-11-16 21:38 UTC
