### ISSUE TITLE
Pod oddity with documentation for the true module

### ISSUE THREAD

**Issue by neilb** [metacpan/metacpan-web#1862] opened 2017-04-06 09:42 UTC
If you look at the [documentation for the true module](https://metacpan.org/pod/true), near the start of the DESCRIPTION section you'll see a blank code sample.

If you look at the raw pod, you'll see this is the following line:

    1;

When I run `perldoc true`, I see that line, so maybe it's a parsing issue with whatever you're using to display pod? Note that just below are similar but slightly different lines, which are being displayed correctly.

I just tried [`https://fastapi.metacpan.org/pod/true`](https://fastapi.metacpan.org/pod/true), and the dodgy line is showing up fine there.

Neil

**Comment by haarg** [comment] 2017-04-06 09:53
The syntax highlighter is eating it.  Dupe of #1228.

**Closed by haarg** 2017-04-06 09:53 UTC
