### ISSUE TITLE
Github issues include PRs

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#2348] opened 2020-07-10 08:41 UTC
When a dist uses Github as its issue tracker, the "Issues" item in the left nav pops up a list of those issues with a count at the top, which is nice. The confusing part is that both the count and the listed items contain not just issues but also PRs and there's no way to distinguish these that I can see without mousing over them and reading the URL.

You might not consider this a problem, which is fair enough. But it just confused me when looking at such a dist to see that there were many issues listed at metacpan which, when clicking through to github were not listed there (because they were actually PRs). It's also maybe a little harsh on some dists to suggest they might have many issues when that might not be the case.

**Comment by haarg** [comment] 2020-07-10 08:50
Duplicate of #2124

**Closed by haarg** 2020-07-10 08:50 UTC
