### ISSUE TITLE
Can't ++ any distribution with "Forbidden" error

### ISSUE THREAD

**Issue by rwp0** [metacpan/metacpan-web#3065] opened 2024-05-12 18:21 UTC
When I want to `++` I get this [error](https://metacpan.org/account/favorite/add?remove=0&release=Authen-TOTP-0.1.0&author=TCHATZI&distribution=Authen-TOTP):

![image](https://github.com/metacpan/metacpan-web/assets/68062695/1384c927-eb2c-48e6-8c4b-ebe8367313cd)

It's something recent, previously I could `++` normally.

I think it's has something to do with [Identities](https://metacpan.org/account/identities):

![image](https://github.com/metacpan/metacpan-web/assets/68062695/8b59ee9d-a6e1-4be6-8305-0c04b748ff2b)

I tried to disable and enable few combinations to remedy this issue with no luck.

**Comment by haarg** [comment] 2024-05-13 23:20
Dupe of #3062

**Closed by haarg** 2024-05-13 23:20 UTC
Labels: type:Bug
