### ISSUE TITLE
Glossary missing for Config.pm ( https://metacpan.org/pod/Config )

### ISSUE THREAD

**Issue by hakonhagland** [metacpan/metacpan-web#1757] opened 2016-07-31 20:10 UTC
Something is wrong with the Glossary section at https://metacpan.org/pod/Config 
It shows up empty, here is a screen shot:

![meta](https://cloud.githubusercontent.com/assets/6708379/17278985/79a11a26-576a-11e6-8f4e-c0bb160a3b5a.png)

If I go to http://perldoc.perl.org/Config.html , I get the whole glossary:

![perldoc](https://cloud.githubusercontent.com/assets/6708379/17278995/b86c0518-576a-11e6-929b-630f5040fa30.png)

There is a script in the root directory of the Perl repository https://github.com/Perl/perl5 called `configpm`. It should generate the file `lib/Config.pod`.

**Comment by oalders** [comment] 2016-08-02 14:40
Thanks for this, @hakonhagland.  When we index Perl (or any other archive) we inflate the archive and index what exists.  If files get created as part of the installation process, they'll never appear on MetaCPAN, since we don't execute any code.  We'd have to make an exception for Perl if we wanted to do something like this.  I'm not sure if that's something the core team has time to focus on at this point.  If someone wanted to talk to us about writing the patch, we could see what might be involved.

**Comment by haarg** [comment] 2017-04-12 00:34
Duplicate of #27

**Closed by haarg** 2017-04-12 00:34 UTC
