### ISSUE TITLE
libnet-1.27 - Net/SMTP.pm - 404 Not Found 

### ISSUE THREAD

**Issue by andk** [metacpan/metacpan-web#1390] opened 2014-10-13 03:20 UTC
https://metacpan.org/pod/release/SHAY/libnet-1.27/lib/Net/SMTP.pm

The above URL was not invented by me, it was offered in the pull down on the page

https://metacpan.org/pod/Net::SMTP

Most likely the reason is this: in the 1.27 release there was a ./Net/SMTP.pm:

-rw-r--r-- 1 sand sand 23540 2014-05-31 00:05:24 Net/SMTP.pm

In 1.28 it moved to lib/

-rw-r--r-- 1 sand sand 27233 2014-10-08 09:33:49 lib/Net/SMTP.pm

HTH&&Thanks,
PS: anecdotal evidence about the context how I discovered this: https://rt.cpan.org/Ticket/Display.html?id=99454

**Comment by haarg** [comment] 2016-11-17 17:19
Dupe of #838

**Closed by haarg** 2016-11-17 17:19 UTC
Labels: Volunteer needed
